### ISSUE TITLE
Fix installation of Empire

### ISSUE THREAD

**Issue by wlayzz** [ShutdownRepo/Exegol-images#29]
Empire need some fix: 
![image](https://user-images.githubusercontent.com/34021743/176301258-5c56cf51-384b-485f-a5dc-dc5906ba3e6d.png)

Installation : `python3 -m pip install .` on /opt/tools/Empire
Command that must be used : `python3 /opt/tools/Empire/empire.py server`

Credentials by default :

- User: empireadmin
- Pass: password123

These need to be changed to fit with other exegol creds.

**Comment by ShutdownRepo** [comment]
@wlayzz can you check if this issue is still one?

**Comment by wlayzz** [comment]
Everything seems OK in the latest release, I close this issue
