### ISSUE TITLE
neo4j required openjdk-11-jre

### ISSUE THREAD

**Issue by cyrinux** [ShutdownRepo/Exegol-images#3]
Hi :)
Maybe it would be usefull to got a neo4j wrapper that do `JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64 neo4j`  ?
Without this, it doesnt start.
Regards

**Comment by ShutdownRepo** [comment]
Thank you for raising the issue. Apparently neo4j requires a fixed version of OpenJDK. Using an alias may not be the most appropriate to fix the issue. I'm looking into Neo4j's documentation ([here](https://neo4j.com/docs/operations-manual/current/installation/linux/debian/#multiple-java-versions)) and will try to fix this

**Comment by ShutdownRepo** [comment]
This issue should be fixed in the latest `nightly` build. Feel free to re-open if needed :)
