### ISSUE TITLE
Msfconsole / Msfvenom missing

### ISSUE THREAD

**Issue by niranc** [ShutdownRepo/Exegol-images#55]
Hi, in the exegol image nightly build v.97209752, msfconsole / msfvenom are missing

![image](https://user-images.githubusercontent.com/20574090/188834516-4e92cc96-4028-4f27-a65b-dd9e592ca151.png)

![image](https://user-images.githubusercontent.com/20574090/188835566-81d5d3f4-77d0-4770-b408-c08fe18ff1a0.png)

**Comment by ShutdownRepo** [comment]
Reading the build logs, I think the error was temporary and up-to-date images do not seem to have this issue 
`Failed to fetch http://downloads.metasploit.com/data/releases/metasploit-framework/apt/dists/lucid/main/binary-amd64/Packages.gz Hash Sum mismatch`
