### ISSUE TITLE
Feature Request: zsh-history-substring-search

### ISSUE THREAD

**Issue by partopronto** [ShutdownRepo/Exegol-images#68]
Hello,

your tool is challanging my setup and I feel the force to contribute now as a user :)  Thx

For years I like to use this plugin as it enables me to quickly look through my long zsh history.
[zsh-history-substring-search](https://github.com/zsh-users/zsh-history-substring-search)

I just write a search term and press arrow-up. See example below (typed 'sort' and pressed up):

![Capture](https://user-images.githubusercontent.com/182337/199687308-60455392-e034-4e88-befa-49669bdf91a4.PNG)

You just continue to press arrow-up until you find what you need. 
I belive the color is helping me to look for what was found faster. Please consider adding it.

**Comment by partopronto** [comment]
I agree your solution is superior to zsh-history-substring-search. I just dont like the shortcut but that's my thing. Thank you gotta try that out in practice.

**Comment by ShutdownRepo** [comment]
> I agree your solution is superior to zsh-history-substring-search. I just dont like the shortcut but that's my thing. Thank you gotta try that out in practice.

Feel free to propose another shortcut or anything else :)

**Comment by ShutdownRepo** [comment]
> I agree your solution is superior to zsh-history-substring-search. I just dont like the shortcut but that's my thing. Thank you gotta try that out in practice.

Feel free to propose another shortcut or anything else :)

**Comment by ShutdownRepo** [comment]
Added the plugin in https://github.com/ShutdownRepo/Exegol-images/commit/bedf8480e9c4a64b424384e7631db4f69498746b
Feel free to re-open the issue if there's anything else you'd like, thank you!!

**Comment by partopronto** [comment]
I am used to press **ArrowUP** for search. 
Will just put `bindkey "${key[Up]}" fzf-history-widget` your _.zshrc_ for now.

**Comment by ShutdownRepo** [comment]
It seems my installation of zsh-history-substring-search doesn't work, reverting the changes. I probably would need to bind keys to make it work but don't have the time to do this now. Binding the upkey to the fzf history may be the best solution though. I'll have to try it a bit
