### ISSUE TITLE
Migrate install.sh

### ISSUE THREAD

**Issue by partopronto** [ShutdownRepo/Exegol-images#71]
Instead of increasing the size and maintainance issues of installer.sh one could delegate the task to python and yaml.
Don't intend to retire the install.sh I think bash is useful where it has its strengths like pipeing and such.

Why not migrate most easy install procedures?
A sample config could look as folIows:

**cat config.yml**
```
ad_tools:
  targetedKerberoast:
    giturl: https://github.com/ShutdownRepo/targetedKerberoast
    install_dest: /opt/tools/
    history: [targetedKerberoast.py -v -d "$DOMAIN" -u user1 -p complexpassword -o Kerberoastables.txt,
              targetedKerberoast.py secondCommandPlaceHolder,
              targetedKerberoast.py thirdCommandPlaceHolder]

web_tools:
   gobuster:
      history: [gobuster dir -w `fzf-wordlists` -u http://192.168.56.0:8000/]
      cmd: go install github.com/OJ/gobuster/v3@latest
   dirsearch:
     giturl: https://github.com/maurosoria/dirsearch
     install_dest: /opt/tools/
     history: [dirsearch -r -w /usr/share/wordlists/seclists/Discovery/Web-Content/quickhits.txt -u "http://$TARGET/"]
```

**cat installer.py**
```
import yaml
with open('config.yml', 'r') as file:
   tools = yaml.safe_load(file)

for tool in tools['ad_tools']:
   for hint in tools['ad_tools'][tool]['history']:
      print(hint)

for tool in tools['web_tools']:
   for hint in tools['web_tools'][tool]['history']:
      print(hint)
```

Just the history output which needs to go to zsh_history:
![3](https://user-images.githubusercontent.com/182337/200116721-e1ff052c-c46e-432c-bc95-550b1848c163.PNG)

**Comment by ShutdownRepo** [comment]
Thank you for initiating the work on this. Like I said in another thread, we are currently working on the next release of Exegol-images. Once this release is over with, we'll be able to move on to this part 👍
Regarding the way tools are installed, we are thinking of creating deb repositories for Exegol. But relying on Python and yaml is also a possibility. We'll see when we get there, we have to make smart choices first, ones that will allow most flexibility and resilience

**Comment by partopronto** [comment]
When you start building deb packets you marry defacto Kali Linux for ever. Staying light and portable leaves more flexibility for the way ahead. I can continue with the port of the installer or do you like me to wait for the release first? Anyways I like to support this project if you care.
